# -*- coding: utf-8 -*-
"""Treść stron: /wgraj-fakture/, /oferta/ i podstrony produktów, /ceny-orientacyjne/."""
from gdp_blocks import *  # noqa

PAGES = {}

# ---------------------------------------------------------------- /wgraj-fakture/
PAGES['wgraj-fakture'] = [
    hero('Wgraj fakturę za gaz i odbierz ofertę w 24 godziny',
         'Wystarczy jedna strona faktury z danymi punktu poboru. Odczytamy z niej taryfę, zużycie i termin obecnej umowy, a w ciągu 24 godzin roboczych [[potwierdzić SLA]] prześlemy ofertę indykatywną w wybranym modelu ceny. Bez telefonu od handlowca, dopóki sam o niego nie poprosisz.',
         None, name='Nagłówek strony'),
    sec('Slot: upload faktury', ref('slot-upload-faktury')),
    sec('Co odczytamy z faktury',
        h('Co odczytamy z Twojej faktury'),
        p('Faktura za gaz zawiera wszystko, czego potrzebujemy do przygotowania oferty. Nie musisz niczego przepisywać.'),
        cols(
            col(h3('Dane punktu poboru'), ul(['Numer punktu poboru (ID PP) i adres', 'Operator systemu dystrybucyjnego', 'Grupa taryfowa dystrybucji, np. W-5 albo W-6 [[potwierdzić przykłady]]', 'Moc umowna, jeśli jest wskazana'])),
            col(h3('Dane zużycia i ceny'), ul(['Zużycie w okresie rozliczeniowym w kWh lub MWh', 'Cena gazu jako paliwa i opłata abonamentowa', 'Opłaty dystrybucyjne stałe i zmienne', 'Akcyza i inne opłaty ustawowe'])),
            col(h3('Dane umowy'), ul(['Obecny sprzedawca', 'Okres rozliczeniowy', 'Termin obowiązywania umowy, jeśli jest podany', 'NIP i dane rejestrowe Twojej firmy'])),
        ),
        helper('Jeśli masz kilka punktów poboru, wgraj po jednej fakturze na każdy z nich albo prześlij zestawienie w jednym pliku.'),
        bg='surface'),
    sec('Co dostaniesz w 24 godziny',
        h('Co dostaniesz w 24 godziny'),
        steps([
            ('Potwierdzenie odczytu', 'E-mail z danymi odczytanymi z faktury do Twojej akceptacji. Poprawiasz je jednym kliknięciem, jeśli coś się nie zgadza.'),
            ('Oferta indykatywna', 'Pasmo ceny w wybranym modelu (stała, indeksowana TGE, transzowy), założenia dotyczące wolumenu i okres obowiązywania oferty.'),
            ('Analiza terminu', 'Najbliższy bezpieczny termin zmiany sprzedawcy wyliczony z Twojej obecnej umowy, o ile ją prześlesz.'),
            ('Lista dokumentów', 'Czego potrzebujemy do podpisania umowy: dane rejestrowe, pełnomocnictwo, ewentualnie umowa dystrybucyjna.'),
        ])),
    sec('Bezpieczeństwo danych',
        h('Jak chronimy dane z Twojej faktury'),
        two(
            [h3('Zakres i cel'), p('Dane z faktury wykorzystujemy wyłącznie do przygotowania oferty i, po Twojej zgodzie, do zawarcia umowy. Nie przekazujemy ich podmiotom trzecim poza operatorem systemu w procedurze zmiany sprzedawcy.'),
             h3('Retencja'), p('Plik faktury przechowujemy przez [[okres retencji]] od przesłania, a po tym czasie usuwamy, chyba że zawrzemy umowę. Szczegóły w <a href="/polityka-prywatnosci/">polityce prywatności</a>.')],
            [h3('Administrator danych'), p('PBM Sp. z o.o., [[adres siedziby]]. Kontakt w sprawach danych osobowych: [[adres e-mail IOD lub kontakt]].'),
             h3('Twoje prawa'), p('Masz prawo dostępu do danych, ich sprostowania, usunięcia i ograniczenia przetwarzania. Wniosek wysyłasz na adres wskazany w polityce prywatności.')],
        ),
        bg='surface'),
    sec('FAQ',
        h('Pytania o wgranie faktury'),
        faq([
            ('Czy wgranie faktury do czegoś mnie zobowiązuje?', 'Nie. Oferta indykatywna jest bezpłatna i niewiążąca. Decyzję podejmujesz po jej otrzymaniu.'),
            ('Jaki plik mogę wgrać?', 'PDF, JPG albo PNG do [[limit rozmiaru]]. Zdjęcie faktury z telefonu wystarczy, jeśli dane są czytelne.'),
            ('Czy oferta w 24 godziny jest wiążąca?', 'Oferta indykatywna pokazuje pasmo ceny i założenia. Ofertę wiążącą dostaniesz po potwierdzeniu wolumenu i terminu, przed podpisaniem umowy.'),
            ('Co, jeśli moja umowa kończy się dopiero za rok?', 'Wyliczymy termin i przypomnimy o nim z wyprzedzeniem. Możesz też zabezpieczyć cenę wcześniej, jeśli wybierzesz umowę z odroczonym startem dostaw [[warunki]].'),
            ('Kto zobaczy moją fakturę?', 'Zespół ofertowy PBM. Dane odczytujemy z pomocą narzędzia do ekstrakcji [[opis rozwiązania w etapie 4]] i weryfikuje je człowiek.'),
            ('Czy muszę wypowiadać obecną umowę samodzielnie?', 'Nie. Po podpisaniu umowy z PBM i pełnomocnictwa wypowiadamy ją za Ciebie w jej terminie i zgłaszamy zmianę do operatora.'),
        ])),
    cta_end(),
]

# ---------------------------------------------------------------- /oferta/
PAGES['oferta'] = [
    hero('Pięć modeli zakupu gazu dla firm',
         'Wybierasz sposób ustalania ceny gazu, nie sprzedawcę „w pakiecie”. Cena stała daje przewidywalność, cena indeksowana do TGE podąża za rynkiem, model transzowy łączy oba podejścia. MŚP mogą dodatkowo wybrać umowę kompleksową, a biometan z aktywów Grupy IMA przygotowujemy.',
         [('Wgraj fakturę', '/wgraj-fakture/'), ('Zobacz pasma cen', '/ceny-orientacyjne/', True)], name='Nagłówek strony'),
    sec('Karty produktów',
        h('Modele ceny'),
        cards([
            {'label': 'Przewidywalność', 'title': 'Cena stała', 'text': 'Jedna stawka za MWh przez cały okres umowy. Budżet gazu zależy tylko od wolumenu.', 'button': ('Cena stała', '/oferta/cena-stala/')},
            {'label': 'Rynek', 'title': 'Cena indeksowana TGE', 'text': 'Cena zmienia się z publikowanym indeksem TGE plus stała marża. Korzystasz ze spadków, ponosisz ryzyko wzrostów.', 'button': ('Cena indeksowana', '/oferta/cena-indeksowana-tge/')},
            {'label': 'Etapami', 'title': 'Model transzowy', 'text': 'Wolumen dzielisz na transze i ustalasz ich cenę w różnych momentach. Uśredniasz cenę zakupu.', 'button': ('Model transzowy', '/oferta/model-transzowy/')},
        ]),
        cards([
            {'label': 'MŚP', 'title': 'Umowa kompleksowa dla MŚP', 'text': 'Sprzedaż i dystrybucja na jednej fakturze, jeśli PBM ma generalną umowę dystrybucyjną z Twoim operatorem. Jeśli nie, pomożemy zawrzeć umowę dystrybucyjną osobno.', 'button': ('Umowa kompleksowa', '/oferta/umowa-kompleksowa-msp/')},
            {'label': 'Wkrótce', 'title': 'Biometan', 'text': 'Biometan z instalacji Grupy IMA Polska. Bez cen i terminów na tym etapie. Zostaw kontakt, a poinformujemy Cię o starcie.', 'button': ('Biometan', '/oferta/biometan/')},
            {'label': 'Nie wiesz, który?', 'title': 'Wgraj fakturę', 'text': 'Na podstawie profilu zużycia wskażemy model, który pasuje do Twojego zakładu, i pokażemy pasmo ceny w każdym z nich.', 'button': ('Wgraj fakturę', '/wgraj-fakture/')},
        ])),
    sec('Tabela porównawcza',
        h('Porównanie modeli'),
        table(['Cecha', 'Cena stała', 'Cena indeksowana TGE', 'Model transzowy', 'Umowa kompleksowa MŚP'], [
            ['Jak ustalana jest cena gazu', 'Stawka z umowy', 'Indeks TGE + marża', 'Średnia z transz', 'Stała albo indeksowana [[warunki]]'],
            ['Kto ponosi ryzyko wzrostu cen', 'PBM', 'Ty', 'Podzielone', 'Zależnie od wariantu'],
            ['Kto korzysta ze spadku cen', 'PBM', 'Ty', 'Podzielone', 'Zależnie od wariantu'],
            ['Wymagane decyzje w trakcie umowy', 'Brak', 'Brak', 'Terminy zamknięcia transz', 'Brak'],
            ['Typowy okres umowy', '[[ ]]', '[[ ]]', '[[ ]]', '[[ ]]'],
            ['Minimalne zużycie roczne', '[[ ]]', '[[ ]]', '[[ ]]', 'do [[X]] GWh'],
            ['Dystrybucja na tej samej fakturze', 'Nie', 'Nie', 'Nie', 'Tak, jeśli PBM ma GUD z Twoim OSD'],
        ], caption='Porównanie ma charakter opisowy. Warunki liczbowe uzupełni PBM.'),
        bg='surface'),
    sec('Dla kogo który model',
        h('Który model pasuje do Twojego zakładu'),
        table(['Twoja sytuacja', 'Rozważ'], [
            ['Budżetujesz koszt gazu na rok naprzód i nie chcesz śledzić notowań', '<a href="/oferta/cena-stala/">Cena stała</a>'],
            ['Masz dział zakupów, który obserwuje rynek, i akceptujesz zmienność', '<a href="/oferta/cena-indeksowana-tge/">Cena indeksowana TGE</a>'],
            ['Zużywasz kilkadziesiąt GWh i więcej, chcesz uśredniać cenę zakupu', '<a href="/oferta/model-transzowy/">Model transzowy</a>'],
            ['Prowadzisz piekarnię, suszarnię, szklarnię albo inną mniejszą firmę i chcesz jednej faktury', '<a href="/oferta/umowa-kompleksowa-msp/">Umowa kompleksowa</a>'],
            ['Raportujesz emisje i szukasz paliwa o niższym śladzie', '<a href="/oferta/biometan/">Biometan (wkrótce)</a>'],
        ])),
    cta_end(),
]

# ---------------------------------------------------------------- produkt: wspólne części

def produkt_faq(items):
    return sec('FAQ', h('Pytania o ten model'), faq(items))


def produkt_zrodla():
    return sources([SRC['pe_4j'], SRC['ure'], SRC['tge']])


# ---------------------------------------------------------------- /oferta/cena-indeksowana-tge/
PAGES['cena-indeksowana-tge'] = [
    hero('Cena gazu indeksowana do TGE',
         'Cena indeksowana to stawka za MWh, która co okres rozliczeniowy zmienia się razem z publikowanym indeksem Towarowej Giełdy Energii, powiększonym o stałą marżę PBM. Korzystasz ze spadków cen hurtowych i ponosisz ryzyko wzrostów. Wybierasz ją, gdy masz kogo, kto obserwuje rynek.',
         [('Wgraj fakturę', '/wgraj-fakture/'), ('Porównaj modele ceny', '/oferta/', True)], crumb_text=crumb('Oferta', '/oferta/', 'Cena indeksowana TGE'), name='Hero produktu'),
    sec('Dla kogo',
        h('Dla kogo jest cena indeksowana'),
        cards([
            {'title': 'Masz osobę odpowiedzialną za zakup energii', 'text': 'Dział zakupów albo energetyk zakładowy śledzi notowania i potrafi ocenić, kiedy ryzyko zmienności jest akceptowalne.'},
            {'title': 'Akceptujesz zmienność kosztu z miesiąca na miesiąc', 'text': 'Budżet zakłada widełki, nie jedną liczbę. Faktura za gaz może się różnić między okresami rozliczeniowymi.'},
            {'title': 'Oczekujesz spadku lub stabilizacji cen', 'text': 'Nie chcesz zamrażać stawki na szczycie rynku. Wolisz płacić cenę bieżącą plus marżę.'},
        ]),
        p('Rozważ inny model, jeśli przewidywalność jest dla Ciebie ważniejsza. Zobacz <a href="/oferta/cena-stala/">cenę stałą</a> lub <a href="/oferta/model-transzowy/">model transzowy</a>, który uśrednia cenę.')),
    sec('Mechanizm',
        h('Jak działa cena indeksowana'),
        p('Cena za MWh w danym okresie rozliczeniowym to wartość indeksu TGE z okresu odniesienia pomnożona przez współczynnik i powiększona o stałą marżę. Wszystkie parametry formuły są zapisane w umowie i nie zmieniają się w jej trakcie.'),
        table(['Element formuły', 'Skąd pochodzi', 'Zmienny w okresie umowy'], [
            ['Indeks TGE, np. indeks rynku dnia następnego albo indeks miesięczny [[wskazać indeks]]', 'Publikacja Towarowej Giełdy Energii', 'Tak, co okres odniesienia'],
            ['Okres odniesienia (dzień, miesiąc, kwartał)', 'Umowa', 'Nie'],
            ['Współczynnik korekty', 'Umowa', 'Nie'],
            ['Marża PBM (zł/MWh)', 'Umowa', 'Nie'],
            ['Opłaty dystrybucyjne, akcyza, podatki', 'Taryfa OSD, przepisy', 'Tak, niezależnie od umowy'],
        ]),
        ol(['Z faktury odczytujemy Twój profil zużycia i grupę taryfową.',
            'Ustalamy w umowie indeks odniesienia, okres odniesienia, współczynnik i marżę [[ ]].',
            'Co okres rozliczeniowy wyliczamy cenę z formuły i pokazujemy jej składniki na fakturze.',
            'W każdej chwili możesz sprawdzić indeks u źródła, na stronie TGE.']),
        bg='surface'),
    sec('Opis indeksu',
        h('Skąd pochodzi indeks'),
        p('Towarowa Giełda Energii publikuje indeksy dla rynku gazu, między innymi dla rynku dnia następnego i rynku terminowego. Indeks, według którego rozliczamy Twoją umowę, wskazujemy w umowie z nazwy i odwołaniem do publikacji giełdy. Nie publikujemy tu wartości indeksów, korzystaj z danych u źródła.'),
        buttons([('Indeksy gazu na stronie TGE', 'https://tge.pl', True)])),
    sec('Ryzyka i ograniczenia',
        h('Ryzyka i ograniczenia'),
        two(
            [h3('Wzrost cen hurtowych'), p('Gdy indeks rośnie, rośnie Twoja stawka. Nie ma górnego limitu, chyba że zapiszemy go w umowie [[warunki]].'),
             h3('Zmienność między okresami'), p('Faktura za gaz może istotnie różnić się z miesiąca na miesiąc. Uwzględnij to w planowaniu płynności.')],
            [h3('Zmiana metodyki indeksu'), p('Jeżeli TGE zmieni albo przestanie publikować indeks, umowa wskazuje indeks zastępczy [[warunki]].'),
             h3('Wcześniejsze rozwiązanie umowy'), p('Może wiązać się z kosztami określonymi w umowie. Dotyczy to także Twojej obecnej umowy, dlatego nigdy nie wypowiadamy jej przed terminem.')],
        )),
    sec('Przykład liczbowy',
        h('Przykład liczbowy'),
        p('Przykład dla zakładu o zużyciu [[ ]] MWh rocznie. Wartości uzupełni PBM na podstawie aktualnych warunków.'),
        table(['Pozycja', 'Wartość', 'Jednostka'], [
            ['Indeks TGE w okresie odniesienia [[nazwa indeksu]]', '[[ ]]', 'zł/MWh'],
            ['Współczynnik korekty', '[[ ]]', '–'],
            ['Marża PBM', '[[ ]]', 'zł/MWh'],
            ['Cena gazu w okresie rozliczeniowym', '[[ ]]', 'zł/MWh netto'],
            ['Zużycie w okresie', '[[ ]]', 'MWh'],
            ['Koszt gazu w okresie', '[[ ]]', 'zł netto'],
        ], caption='Przykład ilustruje formułę, nie ofertę.', numeric=True),
        ref('zastrzezenie-cen'),
        bg='surface'),
    produkt_faq([
        ('Czy cena indeksowana może być wyższa od stałej?', 'Tak, gdy indeks wzrośnie powyżej poziomu, na którym ustalono cenę stałą. Model indeksowany zamienia przewidywalność na udział w ruchach rynku w obie strony.'),
        ('Jak często zmienia się cena?', 'Co okres odniesienia zapisany w umowie, zwykle miesiąc [[potwierdzić]]. Na fakturze widzisz wartość indeksu, współczynnik i marżę.'),
        ('Czy marża może się zmienić w trakcie umowy?', 'Nie. Marża i współczynnik są stałe przez cały okres umowy. Zmienny jest wyłącznie indeks.'),
        ('Czy mogę przejść na cenę stałą w trakcie umowy?', 'Zmiana modelu wymaga aneksu na warunkach z umowy [[ ]]. Jeśli chcesz mieć taką możliwość od początku, rozważ model transzowy.'),
        ('Skąd mam wiedzieć, że wartość indeksu na fakturze jest prawidłowa?', 'Indeksy TGE są publiczne. Na fakturze podajemy nazwę indeksu i okres odniesienia, więc możesz porównać wartość u źródła.'),
        ('Czy dystrybucja też jest indeksowana?', 'Nie. Opłaty dystrybucyjne wynikają z taryfy operatora zatwierdzanej przez Prezesa URE, niezależnie od modelu ceny gazu.'),
    ]),
    produkt_zrodla(),
    cta_end(),
]

# ---------------------------------------------------------------- /oferta/model-transzowy/
PAGES['model-transzowy'] = [
    hero('Model transzowy zakupu gazu',
         'W modelu transzowym dzielisz roczny wolumen na kilka części (transz) i ustalasz cenę każdej z nich w innym momencie, korzystając z notowań rynku terminowego TGE. Cena, którą płacisz, to średnia ważona zamkniętych transz. Wybierasz go, gdy zużywasz dużo gazu i chcesz rozłożyć ryzyko momentu zakupu.',
         [('Zapytaj o model', '/kontakt/'), ('Porównaj modele ceny', '/oferta/', True)], crumb_text=crumb('Oferta', '/oferta/', 'Model transzowy'), name='Hero produktu'),
    sec('Dla kogo',
        h('Dla kogo jest model transzowy'),
        cards([
            {'title': 'Zużywasz od [[X]] GWh rocznie', 'text': 'Wolumen pozwala dzielić zakup na transze o sensownej wielkości, które da się zakontraktować na rynku terminowym.'},
            {'title': 'Chcesz uśrednić cenę zakupu', 'text': 'Nie obstawiasz jednego momentu. Kupujesz w kilku terminach i ograniczasz ryzyko trafienia na szczyt rynku.'},
            {'title': 'Masz kto podejmować decyzje', 'text': 'Model wymaga decyzji o zamknięciu transzy w oknach czasowych. Opiekun PBM przygotowuje rekomendacje, decyzja należy do Ciebie.'},
        ]),
        p('Jeśli nie chcesz podejmować decyzji w trakcie umowy, wybierz <a href="/oferta/cena-stala/">cenę stałą</a> albo <a href="/oferta/cena-indeksowana-tge/">cenę indeksowaną</a>.')),
    sec('Mechanizm',
        h('Jak działa model transzowy'),
        ol(['Ustalamy w umowie roczny wolumen, liczbę transz, ich wielkość i okna czasowe zamykania [[ ]].',
            'W każdym oknie decydujesz, czy zamknąć transzę po bieżącej cenie rynku terminowego plus marża. Opiekun PBM przesyła Ci notowanie i rekomendację.',
            'Transze niezamknięte do końca ostatniego okna rozliczamy według zasady zapisanej w umowie: po cenie indeksowanej albo po cenie z ostatniego dnia okna [[warunki]].',
            'Cena, którą płacisz w okresie dostaw, to średnia ważona cen zamkniętych transz plus marża.']),
        bg='surface'),
    sec('Schemat transz',
        h('Schemat transz'),
        p('Przykładowy podział wolumenu rocznego na cztery transze. Liczbę transz i terminy dopasowujemy do Twojego profilu.'),
        table(['Transza', 'Udział w wolumenie', 'Okno zamknięcia', 'Cena zamknięcia', 'Status'], [
            ['1', '[[ ]] %', '[[miesiąc, rok]]', '[[ ]] zł/MWh', 'Zamknięta'],
            ['2', '[[ ]] %', '[[miesiąc, rok]]', '[[ ]] zł/MWh', 'Zamknięta'],
            ['3', '[[ ]] %', '[[miesiąc, rok]]', '–', 'Otwarta'],
            ['4', '[[ ]] %', '[[miesiąc, rok]]', '–', 'Otwarta'],
            ['Średnia ważona zamkniętych transz', '[[ ]] %', '–', '[[ ]] zł/MWh', '–'],
        ], caption='Schemat ilustruje mechanizm, nie ofertę.', numeric=True)),
    sec('Ryzyka i ograniczenia',
        h('Ryzyka i ograniczenia'),
        two(
            [h3('Decyzja należy do Ciebie'), p('PBM przygotowuje rekomendacje, ale nie podejmuje decyzji za Ciebie i nie gwarantuje, że wybrany moment będzie najkorzystniejszy.'),
             h3('Transze niezamknięte'), p('Wolumen niezakontraktowany w oknach rozliczamy według zasady z umowy. Sprawdź ją przed podpisaniem.')],
            [h3('Odchylenia wolumenu'), p('Zużycie poza pasmem tolerancji [[ ]] rozliczamy według zasad z umowy. Deklaruj wolumen na podstawie historii.'),
             h3('Płynność rynku terminowego'), p('Dla odległych terminów dostawy notowania mogą być mniej płynne. Wpływa to na dostępność cen w oknie.')],
        ),
        bg='surface'),
    sec('Przykład liczbowy',
        h('Przykład liczbowy'),
        p('Przykład dla zakładu o zużyciu [[ ]] GWh rocznie i czterech transzach po [[ ]] %.'),
        table(['Pozycja', 'Wartość', 'Jednostka'], [
            ['Cena transzy 1', '[[ ]]', 'zł/MWh'],
            ['Cena transzy 2', '[[ ]]', 'zł/MWh'],
            ['Cena transzy 3', '[[ ]]', 'zł/MWh'],
            ['Cena transzy 4', '[[ ]]', 'zł/MWh'],
            ['Średnia ważona', '[[ ]]', 'zł/MWh'],
            ['Marża PBM', '[[ ]]', 'zł/MWh'],
            ['Cena końcowa gazu', '[[ ]]', 'zł/MWh netto'],
        ], caption='Przykład ilustruje mechanizm uśredniania, nie ofertę.', numeric=True),
        ref('zastrzezenie-cen')),
    produkt_faq([
        ('Ile transz ma sens?', 'Zwykle od trzech do sześciu [[potwierdzić]]. Więcej transz to lepsze uśrednienie, ale więcej decyzji do podjęcia. Dopasujemy liczbę do wolumenu.'),
        ('Co się stanie, jeśli nie zamknę transzy w oknie?', 'Rozliczymy ją według zasady zapisanej w umowie, np. po cenie indeksowanej. Nigdy nie zamykamy transzy bez Twojej decyzji, chyba że umowa wskazuje inaczej.'),
        ('Czy mogę zamknąć całość w jednej transzy?', 'Tak, wtedy model działa jak cena stała ustalona w wybranym przez Ciebie momencie.'),
        ('Skąd biorą się ceny w oknie?', 'Z notowań rynku terminowego TGE dla produktu odpowiadającego okresowi Twojej dostawy, plus marża PBM zapisana w umowie.'),
        ('Czy potrzebuję konta na giełdzie?', 'Nie. Kontrakty zawiera PBM. Ty otrzymujesz cenę transzy i decydujesz o jej zamknięciu.'),
        ('Czy model transzowy jest dostępny dla MŚP?', 'Dla mniejszych wolumenów rekomendujemy cenę stałą albo indeksowaną. Próg wolumenu podamy w ofercie [[ ]].'),
    ]),
    produkt_zrodla(),
    cta_end(),
]

# ---------------------------------------------------------------- /oferta/umowa-kompleksowa-msp/
PAGES['umowa-kompleksowa-msp'] = [
    hero('Umowa kompleksowa na gaz dla mniejszych firm',
         'Umowa kompleksowa łączy sprzedaż gazu i usługę dystrybucji w jednym dokumencie i na jednej fakturze. Jest dla firm, które zużywają do [[X]] GWh rocznie i chcą jednego rozliczenia bez osobnej umowy z operatorem. Jeżeli PBM nie ma zawartej generalnej umowy dystrybucyjnej z Twoim operatorem, podpiszesz osobno umowę dystrybucyjną; pomożemy w tym.',
         [('Wgraj fakturę', '/wgraj-fakture/'), ('Porównaj modele ceny', '/oferta/', True)], crumb_text=crumb('Oferta', '/oferta/', 'Umowa kompleksowa dla MŚP'), name='Hero produktu'),
    sec('Dla kogo',
        h('Dla kogo jest umowa kompleksowa'),
        cards([
            {'title': 'Piekarnie, suszarnie, przetwórstwo', 'text': 'Gaz jest istotnym kosztem, ale nie masz działu energetycznego. Chcesz jednej faktury i jednego kontaktu.'},
            {'title': 'Szklarnie, ceramika, galwanizernie', 'text': 'Zużycie sezonowe albo zmienne. Umowa kompleksowa z ceną stałą upraszcza planowanie.'},
            {'title': 'Firmy z kilkoma punktami poboru', 'text': 'Jedna umowa może obejmować kilka lokalizacji u tego samego operatora [[warunki]].'},
        ])),
    sec('Umowa dystrybucyjna',
        h('Sprzedaż i dystrybucja: co podpisujesz'),
        p('Gaz dociera do Ciebie siecią operatora systemu dystrybucyjnego (OSD), niezależnie od tego, kto go sprzedaje. Usługę dystrybucji rozlicza się według taryfy OSD zatwierdzanej przez Prezesa URE. Są dwa sposoby jej zakontraktowania.'),
        table(['Wariant', 'Co podpisujesz', 'Ile faktur', 'Kiedy dostępny'], [
            ['Umowa kompleksowa', 'Jedną umowę z PBM: sprzedaż + dystrybucja', 'Jedna', 'Gdy PBM ma generalną umowę dystrybucyjną (GUD-K) z Twoim OSD [[lista operatorów]]'],
            ['Umowa sprzedaży + umowa dystrybucyjna', 'Umowę sprzedaży z PBM i umowę dystrybucyjną z OSD', 'Dwie', 'Zawsze; w zawarciu umowy z OSD pomaga PBM'],
        ]),
        p('<strong>Jeżeli PBM nie ma zawartej generalnej umowy dystrybucyjnej z Twoim operatorem, podpiszesz osobno umowę dystrybucyjną; pomożemy w tym.</strong> Dostawa gazu, sieć i gazomierz pozostają bez zmian w obu wariantach.'),
        bg='surface'),
    sec('Mechanizm',
        h('Jak przebiega zmiana sprzedawcy'),
        steps([
            ('Wgrywasz fakturę', 'Odczytujemy taryfę, zużycie i operatora. W 24 godziny dostajesz ofertę z ceną stałą albo indeksowaną.'),
            ('Podpisujesz umowę i pełnomocnictwo', 'Umowę kompleksową albo sprzedaży, zależnie od operatora. Pełnomocnictwo pozwala nam załatwić formalności.'),
            ('Wypowiadamy obecną umowę w jej terminie', 'Nigdy wcześniej. Zgłaszamy zmianę sprzedawcy do OSD, który ma na nią do 21 dni (art. 4j ust. 6 Prawa energetycznego).'),
            ('Dostajesz jedną fakturę', 'Od pierwszego dnia dostawy rozliczasz gaz i dystrybucję z PBM, a jeśli masz osobną umowę z OSD, dystrybucję rozlicza operator.'),
        ])),
    sec('Ryzyka i ograniczenia',
        h('Ryzyka i ograniczenia'),
        two(
            [h3('Umowa terminowa i jej koszty'), p('Wcześniejsze rozwiązanie umowy zawartej na czas oznaczony może wiązać się z kosztami, które umowa określa wraz ze sposobem ich wyliczenia (art. 4j ust. 3a–3b Prawa energetycznego). Sprawdź to także w swojej obecnej umowie.'),
             h3('Odchylenia wolumenu'), p('Zużycie poza pasmem tolerancji [[ ]] rozliczamy według zasad z umowy.')],
            [h3('Dystrybucja według taryfy'), p('Opłaty dystrybucyjne zmieniają się z taryfą OSD niezależnie od ceny gazu, także na jednej fakturze.'),
             h3('Sprzedawca rezerwowy'), p('W umowie wskazujesz sprzedawcę rezerwowego na wypadek, gdyby sprzedaż ustała. Wyjaśniamy to w <a href="/wiedza/sprzedaz-rezerwowa-gazu-kiedy-grozi-i-ile-kosztuje/">bazie wiedzy</a>.')],
        ),
        bg='surface'),
    sec('Przykład liczbowy',
        h('Przykład liczbowy'),
        p('Przykład dla firmy o zużyciu [[ ]] MWh rocznie w grupie taryfowej [[ ]].'),
        table(['Pozycja faktury', 'Wartość', 'Jednostka'], [
            ['Cena gazu (stała)', '[[ ]]', 'zł/MWh netto'],
            ['Opłata abonamentowa', '[[ ]]', 'zł/miesiąc'],
            ['Opłata dystrybucyjna stała', '[[ ]]', 'zł/miesiąc'],
            ['Opłata dystrybucyjna zmienna', '[[ ]]', 'zł/MWh'],
            ['Akcyza i opłaty ustawowe', '[[ ]]', 'zł/MWh'],
            ['Razem za miesiąc przy zużyciu [[ ]] MWh', '[[ ]]', 'zł netto'],
        ], caption='Przykład ilustruje strukturę jednej faktury, nie ofertę.', numeric=True),
        ref('zastrzezenie-cen')),
    produkt_faq([
        ('Czy zmieni się coś w dostawie gazu?', 'Nie. Ten sam operator, ta sama sieć i gazomierz. Zmienia się sprzedawca i wystawca faktury.'),
        ('Skąd mam wiedzieć, czy PBM ma umowę z moim operatorem?', 'Po wgraniu faktury odczytamy operatora i powiemy Ci, który wariant jest dostępny. Lista operatorów: [[lista operatorów z GUD-K]].'),
        ('Czy umowa kompleksowa jest droższa?', 'Cena gazu jest taka sama jak w umowie sprzedaży. Dystrybucję rozliczamy według taryfy OSD bez narzutu [[potwierdzić]].'),
        ('Czy muszę mieć podpis elektroniczny?', 'Nie. Umowę możesz podpisać elektronicznie albo papierowo [[potwierdzić proces]].'),
        ('Co, jeśli moja umowa ma klauzulę automatycznego przedłużenia?', 'Wyliczymy termin, w którym trzeba złożyć sprzeciw, i złożymy go w Twoim imieniu w odpowiednim czasie. Sprawdź <a href="/kalkulator-wypowiedzenia/">kalkulator terminu</a>.'),
        ('Czy mogę mieć w jednej umowie kilka lokalizacji?', 'Tak, jeśli są u tego samego operatora [[warunki]]. Dla różnych operatorów przygotujemy odpowiednie warianty.'),
    ]),
    sources([SRC['pe_4j'], SRC['pe_5aa'], SRC['ure'], SRC['psg']]),
    cta_end(),
]

# ---------------------------------------------------------------- /oferta/biometan/
PAGES['biometan'] = [
    hero('Biometan z aktywów Grupy IMA Polska',
         'Biometan to oczyszczony biogaz o parametrach gazu ziemnego, który można wtłaczać do sieci. Grupa IMA Polska wytwarza bioetanol, biogaz i biometan we własnych instalacjach. Przygotowujemy ofertę biometanu i mieszanek dla odbiorców przemysłowych. Nie podajemy dziś cen, wolumenów ani terminów.',
         [('Zapisz się na informację', '/kontakt/')], crumb_text=crumb('Oferta', '/oferta/', 'Biometan'), name='Hero produktu'),
    sec('Co to jest',
        h('Czym różni się biometan od gazu ziemnego'),
        table(['Cecha', 'Gaz ziemny', 'Biometan'], [
            ['Pochodzenie', 'Złoża kopalne', 'Fermentacja biomasy i odpadów organicznych, oczyszczanie biogazu'],
            ['Parametry w sieci', 'Zgodne z wymaganiami OSD', 'Zgodne z wymaganiami OSD, ten sam gazomierz i palnik'],
            ['Ślad emisyjny', 'Emisja spalania z paliwa kopalnego', 'Zależny od łańcucha wytwarzania i sposobu rozliczenia certyfikatów'],
            ['Dokumentacja pochodzenia', 'Nie dotyczy', 'Gwarancje pochodzenia albo certyfikaty zrównoważonego rozwoju [[system certyfikacji]]'],
        ])),
    sec('Ograniczenia',
        h('Co musisz wiedzieć przed decyzją'),
        ul(['Sposób zaliczenia biometanu do celów raportowych albo regulacyjnych Twojej firmy zależy od systemu certyfikacji i od przepisów, którym podlegasz. Nie składamy tu żadnych twierdzeń na ten temat.',
            'Dostępność wolumenu zależy od produkcji instalacji Grupy IMA i możliwości przyłączenia do sieci. Nie podajemy terminów.',
            'Cena biometanu i mieszanek zostanie opublikowana w momencie startu oferty, z tym samym zastrzeżeniem cen jak dla gazu ziemnego.']),
        bg='surface'),
    sec('Raport Scope 1 (wkrótce)',
        label('Wkrótce'),
        h('Raport emisji Scope 1 dla każdego punktu poboru'),
        p('Przygotowujemy raport emisji z spalania gazu na potrzeby raportowania CSRD i ETS, wyliczany dla każdego Twojego punktu poboru na podstawie zużycia z faktur. Zakres, metodyka i termin: [[do ustalenia w etapie 4]].'),
        group(h3('Co znajdzie się w raporcie'), ul(['Zużycie gazu per punkt poboru i okres', 'Współczynnik emisji ze wskazaniem źródła [[KOBiZE lub inny]]', 'Emisja CO2 w tonach z podziałem na lokalizacje', 'Udział biometanu, jeśli został dostarczony, zgodnie z dokumentacją pochodzenia']), cls='gdp-karta', name='Zakres raportu (slot)')),
    sec('Formularz zainteresowania (slot)',
        h('Zostaw kontakt, a poinformujemy Cię o starcie'),
        form_card('Zainteresowanie biometanem', 'Bez zobowiązań. Napiszemy, gdy oferta będzie gotowa.',
                  [field('Firma i NIP', 'Nazwa firmy, 10 cyfr'), field('E-mail', 'imie.nazwisko@firma.pl'), field('Szacowane zużycie gazu rocznie', 'MWh albo GWh'), field('Cel', 'Raportowanie / obniżenie emisji / wymagania klientów')],
                  'Zapisz się na informację', name='Formularz zainteresowania (slot)'),
        bg='surface'),
    sources([SRC['red'], SRC['csrd'], SRC['ets'], SRC['kobize']]),
    cta_end(bg=None),
]

# ---------------------------------------------------------------- /ceny-orientacyjne/
PAGES['ceny-orientacyjne'] = [
    hero('Ceny orientacyjne gazu dla firm',
         'Publikujemy pasma cen orientacyjnych dla każdego modelu, żebyś mógł ocenić ofertę przed wysłaniem zapytania. Pasmo to zakres, w którym zwykle mieści się cena gazu jako paliwa dla danego profilu zużycia. Twoja stawka zależy od wolumenu, terminu dostaw i notowań w dniu oferty.',
         [('Wgraj fakturę', '/wgraj-fakture/')], name='Nagłówek strony'),
    sec('Slot: tabela cen', ref('slot-tabela-cen')),
    sec('Dekompozycja ceny',
        h('Z czego składa się Twoja stawka za MWh'),
        p('Na fakturze za gaz cena paliwa to tylko jeden ze składników. Pozostałe wynikają z taryfy operatora i przepisów, więc żaden sprzedawca ich nie zmienia.'),
        table(['Składnik', 'Kto ustala', 'Od czego zależy', 'Na co ma wpływ PBM'], [
            ['Cena gazu jako paliwa', 'Sprzedawca, w umowie', 'Notowania TGE, model ceny, wolumen, okres', 'Tak'],
            ['Marża i opłata handlowa', 'Sprzedawca, w umowie', 'Model ceny, obsługa', 'Tak'],
            ['Opłaty dystrybucyjne stałe i zmienne', 'OSD, taryfa zatwierdzana przez Prezesa URE', 'Grupa taryfowa, moc umowna, zużycie', 'Nie'],
            ['Opłata przesyłowa (w cenie gazu lub osobno)', 'OSP, taryfa zatwierdzana przez Prezesa URE', 'Sposób kontraktowania', 'Częściowo'],
            ['Akcyza', 'Przepisy prawa', 'Przeznaczenie gazu, zwolnienia [[do weryfikacji]]', 'Nie'],
            ['Inne opłaty ustawowe', 'Przepisy prawa', 'Aktualne regulacje', 'Nie'],
            ['VAT', 'Przepisy prawa', 'Stawka ustawowa', 'Nie'],
        ]),
        bg='surface'),
    sec('Jak czytać pasma',
        h('Jak czytać pasma'),
        two(
            [h3('Dolna granica'), p('Cena dla profilu o stabilnym, wysokim zużyciu, długim okresie umowy i korzystnym momencie zakupu.'),
             h3('Górna granica'), p('Cena dla profilu o niskim albo sezonowym zużyciu, krótkim okresie umowy i mniej korzystnym momencie zakupu.')],
            [h3('Co nie jest w paśmie'), p('Dystrybucja, akcyza, podatki i opłaty ustawowe. Doliczasz je według taryfy swojego operatora i przepisów.'),
             h3('Data aktualizacji'), p('Pasma aktualizujemy [[częstotliwość]]. Data ostatniej aktualizacji jest pod tabelą. Oferta indykatywna bazuje na notowaniach z dnia jej przygotowania, nie z dnia aktualizacji pasm.')],
        )),
    sec('Zastrzeżenie', ref('zastrzezenie-cen'), bg='surface', pad='50'),
    sec('FAQ',
        h('Pytania o ceny orientacyjne'),
        faq([
            ('Dlaczego nie podajecie jednej ceny?', 'Cena gazu zależy od profilu zużycia, terminu dostaw i notowań w dniu oferty. Jedna liczba byłaby myląca. Pasmo pokazuje realny zakres.'),
            ('Czy oferta może wypaść poza pasmem?', 'Tak, przy nietypowym profilu albo dużej zmianie notowań od ostatniej aktualizacji. Wtedy wyjaśnimy, dlaczego.'),
            ('Czy pasma dotyczą też dystrybucji?', 'Nie. Opłaty dystrybucyjne wynikają z taryfy Twojego operatora, dostępnej na stronie URE i operatora.'),
            ('Jak porównać pasmo z moją obecną fakturą?', 'Znajdź na fakturze pozycję „paliwo gazowe” albo „cena gazu” w zł/MWh (czasem zł/kWh, pomnóż przez 1000) i porównaj z pasmem dla swojego profilu.'),
        ])),
    sources([SRC['tge'], SRC['ure'], ('Ustawa o podatku akcyzowym (zwolnienia dla gazu do celów opałowych w działalności)', 'https://isap.sejm.gov.pl')]),
    cta_end(),
]
